FROM gradle:8.5-jdk17 AS build

ARG DB_URL
ENV DB_URL=$DB_URL
ARG DB_NAME
ENV DB_NAME=$DB_NAME
ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD
ARG GEMINI_PROJECT_ID
ENV GEMINI_PROJECT_ID=$GEMINI_PROJECT_ID
ARG GEMINI_LOCATION
ENV GEMINI_LOCATION=$GEMINI_LOCATION
ARG GEMINI_API_KEY
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ARG TRAVEL_API_KEY
ENV TRAVEL_API_KEY=$TRAVEL_API_KEY
ARG SENTRY_DSN
ENV SENTRY_DSN=$SENTRY_DSN
ARG SENTRY_ENV
ENV SENTRY_ENV=$SENTRY_ENV
ARG FIREBASE_API_KEY
ENV FIREBASE_API_KEY=$FIREBASE_API_KEY
ARG WEATHER_API_KEY
ENV WEATHER_API_KEY=$WEATHER_API_KEY


COPY . /app
WORKDIR /app
RUN apt-get update && apt-get install -y maven
RUN chmod +x ./gradlew
RUN ./gradlew clean build -x test

FROM openjdk:17 AS final
COPY --from=build /app/build/libs/route.jar /app/greenroute.jar
EXPOSE 80
CMD ["java", "-jar", "/app/greenroute.jar"]
