name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: chmod +x gradlew
      - run: ./gradlew test

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: sonar-${{ runner.os }}-${{ hashFiles('build.gradle') }}
          restore-keys: sonar-${{ runner.os }}-

      - name: Code quality and coverage analysis
        run: |
          ./gradlew sonarqube --info \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=${{ vars.SONAR_ORG }} \
            -Dsonar.projectKey=${{ vars.SONAR_PJ_KEY }} \
            -Dsonar.projectName=${{ vars.SONAR_PJ_NAME }} \
            -Dsonar.sources=src/main/java \
            -Dsonar.tests=src/test/java \
            -Dsonar.java.binaries=build/classes/java/main \
            -Dsonar.java.test.binaries=build/classes/java/test \
            -Dsonar.junit.reportPaths=build/test-results/test \
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml \
            -Dsonar.java.checkstyle.reportPaths=build/reports/checkstyle/main.xml,build/reports/checkstyle/test.xml

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - run: chmod +x format.sh
      - run: ./format.sh && git diff --exit-code